--WHERE절
SELECT * FROM EMPLOYEES;

--BETWEEN~AND, IN, LIKE
SELECT * FROM employees WHERE SALARY BETWEEN 6000 AND 9000; --이상~이하
select * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '08/01/01' AND '08/12/31';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (10, 20, 30, 40, 50);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('ST_MAN', 'IT_PROG');

SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE 'IT%';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%12%';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '___05%';
SELECT * FROM EMPLOYEES WHERE EMAIL LIKE '_A%';

--NOT, OR, AND
SELECT * FROM EMPLOYEES WHERE NOT SALARY >= 6000; --NOT은 <>과 동일한 표현

--IS NULL, IS NOT NULL
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL; -- = NULL (X)

--AND가 OR 보다 우선순위가 빠름
SELECT * FROM EMPLOYEES WHERE SALARY >= 6000 AND SALARY <= 12000; --BETWEEN 6000 AND 12000
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR SALARY >= 6000;
SELECT * FROM EMPLOYEES WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR') AND SALARY >= 6000;

-- ORDER BY 컬럼 (앨리어스)
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE; --날짜 기준 ASC
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC;

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'ST_MAN') ORDER BY FIRST_NAME DESC;
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 6000 AND 12000 ORDER BY EMPLOYEE_ID;

--ALIAS도 ORDER절에 사용할 수 있음
SELECT FIRST_NAME, SALARY * 12 AS PAY FROM employees ORDER BY PAY ASC;

--정렬 여러개 ,로 나열
SELECT FIRST_NAME, SALARY, JOB_ID FROM EMPLOYEES ORDER BY JOB_ID ASC, SALARY DESC;











