--문제1
SELECT * FROM DEPTS;

INSERT INTO DEPTS VALUES (280, '개발', NULL, 1800);
INSERT INTO DEPTS VALUES (290, '회계부', NULL,1800);
INSERT INTO DEPTS VALUES (300, '재정', 301, 1800);
INSERT INTO DEPTS VALUES (310, '인사', 302, 1800);
INSERT INTO DEPTS VALUES (320, '영업', 303, 1700);
COMMIT;
--문제2
UPDATE DEPTS
SET DEPARTMENT_NAME = 'IT bank'
WHERE DEPARTMENT_NAME = 'IT Support';

UPDATE DEPTS
SET MANAGER_ID = '301'
WHERE DEPARTMENT_ID = 290;

UPDATE DEPTS
SET DEPARTMENT_NAME = 'IT Help',
    MANAGER_ID = 303,
    LOCATION_ID = 1800
WHERE DEPARTMENT_NAME = 'IT Helpdesk';

UPDATE DEPTS
SET MANAGER_ID = 301
WHERE DEPARTMENT_NAME IN ('재정', '인사', '영업');

--문제3
DELETE FROM DEPTS
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPTS WHERE DEPARTMENT_NAME = '영업');

DELETE FROM DEPTS
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPTS WHERE DEPARTMENT_NAME = 'NOC');

--문제4
CREATE TABLE DEPTSCOPY AS (SELECT * FROM DEPTS WHERE 1 = 1);
SELECT * FROM DEPTSCOPY;

DELETE FROM DEPTSCOPY
WHERE DEPARTMENT_ID > 200;
COMMIT;

UPDATE DEPTSCOPY
SET MANAGER_ID = 100
WHERE MANAGER_ID IS NOT NULL;

MERGE INTO DEPTSCOPY DS
USING (SELECT * FROM DEPARTMENTS) D
ON (DS.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHEN MATCHED THEN
    UPDATE SET DS.DEPARTMENT_NAME = D.DEPARTMENT_NAME,
               DS.MANAGER_ID = D.MANAGER_ID,
               DS.LOCATION_ID = D.LOCATION_ID
WHEN NOT MATCHED THEN
    INSERT VALUES(D.DEPARTMENT_ID,
                  D.DEPARTMENT_NAME,
                  D.MANAGER_ID,
                  D.LOCATION_ID);
    
select * from jobs;
    
CREATE TABLE JOBS_IT AS (SELECT * FROM JOBS WHERE MIN_SALARY > 6000);

COMMIT;

INSERT INTO JOBS_IT VALUES('IT_DEV','아이티개발팀',6000,20000);
INSERT INTO JOBS_IT VALUES('NET_DEV', '네트워크개발팀', 5000, 20000);
INSERT INTO JOBS_IT VALUES('SEC_DEV', '보안개발팀', 6000, 19000);

MERGE INTO JOBS_IT JI
USING JOBS J
ON (JI.JOB_ID = J.JOB_ID)
WHEN MATCHED THEN
    UPDATE SET JI.MIN_SALARY = J.MIN_SALARY,
               JI.MAX_SALARY = J.MAX_SALARY
WHEN NOT MATCHED THEN
    INSERT VALUES (J.JOB_ID,
                   J.JOB_TITLE,
                   J.MIN_SALARY,
                   J.MAX_SALARY
                    );
                    
SELECT * FROM JOBS_IT;









